export const GET_ALL_EVENTS = 'GET_ALL_EVENTS';
export const GET_NUMBER_OF_SELECTED_EVENTS = 'GET_NUMBER_OF_SELECTED_EVENTS';
export const ADD_EVENT_TO_SELECTION_AREA = 'ADD_EVENT_TO_SELECTION_AREA';
export const DELETE_EVENT_FROM_CART = 'DELETE_EVENT_FROM_CART';
